name: scoop-technologies-website
services:
- name: website
  source_dir: /
  github:
    repo: Treemonkey1234/Scoop_Technologies_Website
    branch: main
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
domains:
- domain: scoopsocials.com
  type: PRIMARY 